# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QDateTime
from eightcode import EightCode
from threading import Timer

a = [1, 2, 8, 0, 6, 3, 7, 5, 4]
b = [1, 2, 3, 8, 0, 4, 7, 6, 5]
width = 3


class Ui_Dialog(object):
    def init_LCD(self):
        self.lcdNumber_2.display(1)
        self.lcdNumber_9.display(7)
        self.lcdNumber_5.display(3)
        self.lcdNumber_6.display(4)
        self.lcdNumber_1.display(0)
        self.lcdNumber_3.display(2)
        self.lcdNumber_4.display(8)
        self.lcdNumber_8.display(5)
        self.lcdNumber_0.display(6)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 465)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 140, 64, 61))
        self.lcdNumber_2.setDigitCount(1)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("intValue", 1)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_9.setGeometry(QtCore.QRect(20, 280, 64, 61))
        self.lcdNumber_9.setDigitCount(1)
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setProperty("intValue", 7)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_1 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_1.setGeometry(QtCore.QRect(20, 210, 64, 61))
        self.lcdNumber_1.setDigitCount(1)
        self.lcdNumber_1.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_1.setProperty("intValue", 0)
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_3.setGeometry(QtCore.QRect(90, 140, 64, 61))
        self.lcdNumber_3.setDigitCount(1)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setProperty("intValue", 2)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_0 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_0.setGeometry(QtCore.QRect(90, 210, 64, 61))
        self.lcdNumber_0.setDigitCount(1)
        self.lcdNumber_0.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_0.setProperty("intValue", 6)
        self.lcdNumber_0.setObjectName("lcdNumber_0")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_8.setGeometry(QtCore.QRect(90, 280, 64, 61))
        self.lcdNumber_8.setDigitCount(1)
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setProperty("intValue", 5)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_4.setGeometry(QtCore.QRect(160, 140, 64, 61))
        self.lcdNumber_4.setAcceptDrops(False)
        self.lcdNumber_4.setDigitCount(1)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setProperty("intValue", 8)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_6.setGeometry(QtCore.QRect(160, 280, 64, 61))
        self.lcdNumber_6.setDigitCount(1)
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("intValue", 4)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_5.setGeometry(QtCore.QRect(160, 210, 64, 61))
        self.lcdNumber_5.setDigitCount(1)
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("intValue", 3)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(280, 120, 91, 23))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 170, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 220, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 270, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 320, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 370, 91, 23))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(lambda: self.get_value(5))
        self.pushButton_6.clicked.connect(self.show_path)
        self.pushButton.clicked.connect(lambda: self.get_value(4))
        self.pushButton_3.clicked.connect(lambda: self.get_value(1))
        self.pushButton_4.clicked.connect(lambda: self.get_value(2))
        self.pushButton_5.clicked.connect(lambda: self.get_value(2))
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "八数码问题"))
        self.pushButton.setText(_translate("Dialog", "宽度优先搜索"))
        self.pushButton_2.setText(_translate("Dialog", "深度优先搜索"))
        self.pushButton_3.setText(_translate("Dialog", "估价函数一"))
        self.pushButton_4.setText(_translate("Dialog", "估价函数二"))
        self.label.setText(_translate("Dialog", "八数码问题演示"))
        self.pushButton_5.setText(_translate("Dialog", "估价函数三"))
        self.pushButton_6.setText(_translate("Dialog", "展示过程"))

    def set_value(self, item):
        self.lcdNumber_2.display(item[0])
        self.lcdNumber_2.display(item[0])
        self.lcdNumber_9.display(item[6])
        self.lcdNumber_5.display(item[5])
        self.lcdNumber_6.display(item[8])
        self.lcdNumber_1.display(item[3])
        self.lcdNumber_3.display(item[1])
        self.lcdNumber_4.display(item[2])
        self.lcdNumber_8.display(item[7])
        self.lcdNumber_0.display(item[4])
    def get_value(self,value):
        self.init_LCD()
        self.pushButton.setEnabled(False)
        self.pushButton_2.setEnabled(False)
        self.pushButton_3.setEnabled(False)
        self.pushButton_4.setEnabled(False)
        self.pushButton_5.setEnabled(False)
        self.pushButton_6.setEnabled(False)
        global a
        global b
        global width
        ans = EightCode(a, b, typeScout=value)
        ans.find_path()
        self.ans = ans.lists
        self.pushButton_6.setEnabled(True)
    def test(self):
        self.runTime += 1
        if (self.runTime >= len(self.ans)):
            self.timer.stop()
            return
        self.set_value(self.ans[self.runTime])
    def show_path(self):
        # self.set_value(self.ans[1])
        self.timer = QTimer()
        self.runTime = 0
        self.timer.timeout.connect(self.test)
        self.timer.start(1000)
        self.pushButton.setEnabled(True)
        self.pushButton_2.setEnabled(True)
        self.pushButton_3.setEnabled(True)
        self.pushButton_4.setEnabled(True)
        self.pushButton_5.setEnabled(True)
        self.pushButton_6.setEnabled(True)
